drop database if exists lab2 CASCADE;

create database IF NOT EXISTS lab2;

use lab2;

CREATE EXTERNAL TABLE IF NOT EXISTS sales (
ORDERNUMBER BIGINT, 
QUANTITYORDERED INT, 
PRICEEACH FLOAT,
ORDERLINENUMBER INT,
SALES DOUBLE,
ORDERDATE STRING,
STATUS STRING,
QTR_ID INT,
MONTH_ID INT,
YEAR_ID INT,
PRODUCTLINE STRING,
MSRP INT,
PRODUCTCODE STRING,
CUSTOMERNAME STRING,
PHONE STRING,
ADDRESSLINE1 STRING,
ADDRESSLINE2 STRING,
CITY STRING,
STATE STRING,
POSTALCODE STRING,
COUNTRY STRING,
TERRITORY STRING,
CONTACTLASTNAME STRING,
CONTACTFIRSTNAME STRING,
DEALSIZE STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';

show databases;
show tables;
Describe formatted sales;

LOAD DATA INPATH '/user/osboxes/sales_data_sample.csv' INTO table sales;

select COUNTRY, COUNT(COUNTRY) from sales group by COUNTRY;

select COUNTRY, SUM(QUANTITYORDERED), STATUS from sales where STATUS = 'shipped' group by COUNTRY;

select DEALSIZE, COUNT(DEALSIZE) from sales group by DEALSIZE;

set hive.exec.dynamic.partition.mode=nonstrict;

CREATE EXTERNAL TABLE IF NOT EXISTS partitioned_sales (
ORDERNUMBER BIGINT, 
QUANTITYORDERED INT, 
PRICEEACH FLOAT,
ORDERLINENUMBER INT,
SALES DOUBLE,
ORDERDATE STRING,
QTR_ID INT,
MONTH_ID INT,
YEAR_ID INT,
PRODUCTLINE STRING,
MSRP INT,
PRODUCTCODE STRING,
CUSTOMERNAME STRING,
PHONE STRING,
ADDRESSLINE1 STRING,
ADDRESSLINE2 STRING,
CITY STRING,
STATE STRING,
POSTALCODE STRING,
COUNTRY STRING,
TERRITORY STRING,
CONTACTLASTNAME STRING,
CONTACTFIRSTNAME STRING,
DEALSIZE STRING)
partitioned  by (STATUS STRING);

insert overwrite table partitioned_sales  partition(STATUS) select *  from sales;

describe formatted partitioned_sales;
